title: A Case Study to Consider Transformers Models as a Tool for Character Analysis
description: Finn the Human from Adventure Time
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight