title: Considering Transformers Models as a Tool for Character Analysis with Finn the Human
description: a guide for beginners and familiars in using a use-case specific, fine-tuned, pre-trained large language model
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight